repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
        - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
        - id: flake8
